Repository PGBSNH19/project-g2, pull requests merged in 2020-12, with the labels that each got.

#2 Add YAML-file for CI
  .github/workflows/BuildSln.yml
  .github/workflows/learn-github-actions.yml
Labels: CI/CD

#3 Setup tests in ci
  .github/workflows/BuildSln.yml
  .github/workflows/Test_.Net5_Build_Pipeline.yml
  KNet/KNet.Tests/KNet.Tests.csproj
  KNet/KNet.Tests/UnitTest1.cs
Labels: CI/CD

#29 [G2-91]Add workflow yml file setting up CI pipeline for development branch
  .github/workflows/CIDevelopment.yml
Labels: CI/CD

#37 [G2-92] Add release pipeline for main
  .github/workflows/ReleasePipeline.yml
Labels: CI/CD

#40 [G2-92] [G2-93] [G2-94] Cleanup Workflows in Main
  .github/workflows/BuildSln.yml
  .github/workflows/CIForStage.yml
  .github/workflows/ReleasePipeline.yml
  .github/workflows/dotnet.yml
Labels: CI/CD

#50 [G2-117] Get basic modal to work
  KNet/KNet.Web/App.razor
  KNet/KNet.Web/Pages/Index.razor
  KNet/KNet.Web/Shared/AdModal.razor
Labels: Blazor, Frontend

#53 [G2-121] Add flag button to ad modal for flagging bad content
  KNet/KNet.Web/Shared/AdModal.razor
Labels: Blazor, Frontend

#52 G2 38 nav bar user menu
  KNet/KNet.Web/Shared/NavMenu.razor
Labels: Blazor, Frontend

#55 Create WEB_Release_Pipeline.yml
  .github/workflows/WEB_Release_Pipeline.yml
Labels: CI/CD

#54 Refactoring of API release pipeline
  .github/workflows/API_Release_Pipeline.yml
Labels: CI/CD

#56 Delete ReleasePipeline.yml
  .github/workflows/ReleasePipeline.yml
  .github/workflows/WEB_Release_Pipeline.yml
Labels: CI/CD

#57 Update and rename CIStaging.yml to API_Staging_Pipeline.yml
  .github/workflows/API_Staging_Pipeline.yml
  .github/workflows/CIDevelopment.yml
  .github/workflows/CIStaging.yml
  .github/workflows/WEB_Staging_Pipeline.yml
Labels: CI/CD

#58 Update and rename CIStaging.yml to API_Development_Pipeline.yml
  .github/workflows/API_Development_Pipeline.yml
  .github/workflows/CIStaging.yml
  .github/workflows/WEB_Development_Pipeline.yml
Labels: CI/CD

#59 Create Release_CI_Pipeline.yml
  .github/workflows/Release_CI_Pipeline.yml
Labels: CI/CD

#62 Update API_Staging_Pipeline.yml
  .github/workflows/API_Staging_Pipeline.yml
Labels: CI/CD

#63 Update API_Development_Pipeline.yml
  .github/workflows/Development_API_Pipeline.yml
  .github/workflows/Development_CI_Pipeline.yml
  .github/workflows/Development_WEB_Pipeline.yml
  .github/workflows/Release_API_Pipeline.yml
  .github/workflows/Release_CI_Pipeline.yml
  .github/workflows/Release_WEB_Pipeline.yml
  .github/workflows/Staging_API_Pipeline.yml
  .github/workflows/Staging_CI_Pipeline.yml
  .github/workflows/Staging_WEB_Pipeline.yml
Labels: CI/CD

#66 Fixing up pipelines
  .github/workflows/Development_CI_Pipeline.yml
  .github/workflows/Release_CI_Pipeline.yml
  .github/workflows/Staging_CI_Pipeline.yml
Labels: CI/CD

#67 Fixing up pipelines
  .github/workflows/Development_API_Pipeline.yml
  .github/workflows/Development_CI_Pipeline.yml
  .github/workflows/Development_WEB_Pipeline.yml
  .github/workflows/Release_API_Pipeline.yml
  .github/workflows/Release_CI_Pipeline.yml
  .github/workflows/Release_WEB_Pipeline.yml
  .github/workflows/Staging_API_Pipeline.yml
  .github/workflows/Staging_CI_Pipeline.yml
  .github/workflows/Staging_WEB_Pipeline.yml
Labels: CI/CD

#51 Add document explaining our workflow philosophy
  Documentation/General development workflow.md
Labels: documentation

#79 [G2-106]CreateAdvertPage
  KNet/KNet.Web/Pages/Advert.razor
  KNet/KNet.Web/Shared/NavMenu.razor
Labels: Blazor, Frontend

#80 [G2-142] Azure db fix
  KNet/KNet.API/KNet.API.csproj
  KNet/KNet.API/Program.cs
  KNet/KNet.API/Startup.cs
Labels: Azure, Database

#77 Advert controller unit tests
  .github/workflows/Development_CI_Pipeline.yml
  KNet/KNet.API/KNet.API.csproj
  KNet/KNet.APITests/Controllers/AdvertControllerTests.cs
  KNet/KNet.APITests/KNet.API.Tests.csproj
  KNet/KNet.APITests/KNet.APITests.csproj
  KNet/KNet.Tests/UnitTest1.cs
  KNet/KNet.sln
Labels: Unit Tests
