Repository PGBSNH19/project-g2, pull requests merged in 2021-01, with the labels that each got.

#83 My adverts view
  KNet/KNet.API/Controllers/V1/AdvertController.cs
  KNet/KNet.API/KNet.API.csproj
  KNet/KNet.API/Program.cs
  KNet/KNet.API/Startup.cs
  KNet/KNet.Web/Controllers/AdvertController.cs
  KNet/KNet.Web/Data/AdvertModel.cs
  KNet/KNet.Web/Data/CategoryModel.cs
  KNet/KNet.Web/Data/Entity.cs
  KNet/KNet.Web/Data/User.cs
  KNet/KNet.Web/Data/WeatherForecast.cs
  KNet/KNet.Web/Data/WeatherForecastService.cs
  KNet/KNet.Web/Pages/CreateAdvert.razor
  KNet/KNet.Web/Pages/FetchData.razor
  KNet/KNet.Web/Pages/MyAdverts.razor
  KNet/KNet.Web/Program.cs
  KNet/KNet.Web/Shared/AdModal.razor
  KNet/KNet.Web/Shared/AdvertComponent.razor
  KNet/KNet.Web/Shared/EditAdModal.razor
  KNet/KNet.Web/Shared/NavMenu.razor
  KNet/KNet.Web/Startup.cs
  KNet/KNet.Web/_Imports.razor
Labels: Blazor, Frontend

#94 Save us plox: Reverting repo to hopefully working state
  KNet/KNet.API/Context/AppDbContext.cs
Labels: Save Us, bug

#97 Update Development_API_Pipeline.yml
  .github/workflows/Development_API_Pipeline.yml
Labels: Azure, CI/CD

#98 Update Development_API_Pipeline.yml
  .github/workflows/Development_API_Pipeline.yml
Labels: CI/CD

#99 Update Development_API_Pipeline.yml
  .github/workflows/Development_API_Pipeline.yml
Labels: CI/CD

#100 Update dev apicd
  .github/workflows/Development_API_Pipeline.yml
  .github/workflows/Development_CI_Pipeline.yml
  .github/workflows/Development_WEB_Pipeline.yml
  .github/workflows/Release_API_Pipeline.yml
  .github/workflows/Release_CI_Pipeline.yml
  .github/workflows/Release_WEB_Pipeline.yml
  .github/workflows/Staging_API_Pipeline.yml
  .github/workflows/Staging_WEB_Pipeline.yml
  Documentation/General development workflow.md
Labels: CI/CD

#101 Update url's to reflect new FQDN names in azure. Makes web connect to…
  KNet/KNet.Web/Startup.cs
Labels: Azure, Frontend

#102 Development
  .github/workflows/Development_API_Pipeline.yml
  .github/workflows/Development_CI_Pipeline.yml
  .github/workflows/Development_WEB_Pipeline.yml
  .github/workflows/Release_API_Pipeline.yml
  .github/workflows/Release_CI_Pipeline.yml
  .github/workflows/Release_WEB_Pipeline.yml
  .github/workflows/Staging_API_Pipeline.yml
  .github/workflows/Staging_WEB_Pipeline.yml
  Documentation/General development workflow.md
  KNet/KNet.API/Context/AppDbContext.cs
  KNet/KNet.API/Services/AzureKeyVaultService.cs
  KNet/KNet.Web/Startup.cs
Labels: Stage from dev

#104 Update Release_API_Pipeline.yml
  .github/workflows/Release_API_Pipeline.yml
Labels: CI/CD

#108 Ad modal [G2-116]
  KNet/KNet.Web/Shared/AdModal.razor
Labels: Frontend

#110 [G2-104] My adverts
  KNet/KNet.API/Context/AppDbContext.cs
  KNet/KNet.API/Controllers/V1/AdvertController.cs
  KNet/KNet.Web/Controllers/AdvertController.cs
  KNet/KNet.Web/Startup.cs
Labels: Blazor, Frontend

#111 My adverts delete button
  KNet/KNet.Web/Pages/MyAdverts.razor
  KNet/KNet.Web/Shared/AdvertComponent.razor
Labels: Blazor, Frontend

#112 Stage dev code
  KNet/KNet.API/Context/AppDbContext.cs
  KNet/KNet.API/Controllers/V1/AdvertController.cs
  KNet/KNet.Web/Controllers/AdvertController.cs
  KNet/KNet.Web/Pages/MyAdverts.razor
  KNet/KNet.Web/Shared/AdvertComponent.razor
  KNet/KNet.Web/Startup.cs
Labels: Stage from dev

#114 [G2-26] Add updated readme file to documents folder
  README.md
Labels: documentation
